config/routes.rb
require "resque_web"

Flow::Application.routes.draw do
  resources :documents do
    post 'analyze', on: :member
    post 'extract', on: :member
  end

  root to: 'pages#root'

  mount ResqueWeb::Engine => "/resque_web"
end

app/models/document.rb
require 'ots'

class Document < ActiveRecord::Base
  has_attached_file :source, :path => ':rails_root/public/documents:url'
  # validates_attachment :document, content_type: { content_type: "application/pdf" }
  #

  # after_post_process :extract_content

  def sentences
    @sentences ||= self.content.try { |c| c.split('.').reject { |s| s.blank? } }
  end

  def brief_summary
    self.summary.try { |s| s[0,255] }
  end

  def analyze
    summarize
    # keywords
  end

  def summarize
    if self.content.blank?
      self.errors.add :base, 'cannot summarize without content'
      return false
    end

    Rails.logger.info "=== kicking off summarize content job"
    # self.worker_id = SummarizeContentJob.create(:document_id => self.id)
    # Rails.logger.info "--- using worker id: #{self.worker_id}"
    Resque.enqueue SummarizeContentJob, self.id # :document_id => self.id

    true
  end

  def extract_content

    unless self.content.blank? 
      self.errors.add :base, 'cannot analyze with content present' 
      return false
    end

    Rails.logger.info "=== kicking off extract pdf content job"
    self.update_attribute :worker_id, ExtractPDFContentJob.create(:document_id => self.id)
    Rails.logger.info "--- using worker id: #{self.worker_id}"
    
    true
  end

  def worker_progress
    status = Resque::Plugins::Status::Hash.get(self.worker_id)
    status.nil? ? nil : status.pct_complete
    # if status && status.working?
    #   "(#{self.worker_id}) #{status.pct_complete}%"
    # else
    #   "(#{self.worker_id}) Not working"
    # end
  end

  def parsed_content
    @parsed_content ||= OTS.parse(self.content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :extract, :analyze, :destroy]

  def index
    @documents = Document.all
  end

  def show
  end

  def new
    @document = Document.new
  end

  def edit
  end

  def create
    @document = Document.new(document_params)

    if @document.save
      redirect_to @document, notice: 'Document was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @document.update(document_params)
      redirect_to @document, notice: 'Document was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def extract
    if @document.extract_content
      redirect_to @document, notice: 'Extraction has successfully been initiated.'
    else
      render action: 'show'
    end
  end

  def analyze
    if @document.summarize
      redirect_to @document, notice: 'Analysis has successfully been initiated.'
    else
      render action: 'show'
    end
  end

  def destroy
    @document.destroy
    redirect_to documents_url, notice: 'Document was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def document_params
      params.require(:document).permit(:name, :description, :content, :source)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def root
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_class(alert_type)
    alert_type = {
      alert: 'error',
      notice: 'info'
    }.fetch(alert_type, alert_type.to_s)
    "alert-#{alert_type}"
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_actions.html.slim
/- if can? :edit, @document
= link_to 'Edit', edit_document_path(document), class: 'btn btn-mini'
- unless document.content.blank?
  = link_to 'Analyze', analyze_document_path(document), method: :post, data: { confirm: 'Really kickoff analysis?' }, class: 'btn btn-info'
- unless document.content.present?
  = link_to 'Extract', extract_document_path(document), method: :post, data: { confirm: 'Really kickoff analysis?' }, class: 'btn btn-info'
/- if can? :destroy, document
= link_to 'Destroy', document_path(document), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-mini btn-danger'

app/views/documents/_document.html.slim
i.icon.icon-5x.icon-file-text.muted
p.lead
  = link_to document.name, document_path(document)

small.text-muted summary
p= document.brief_summary

b.text-center Random Sentence
p.text-success 
  i.icon.icon-quote-left.muted.pull-left
  = document.sentences.sample

== render 'actions', :document => document

app/views/documents/_form.html.slim
= simple_form_for(@document) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, autofocus: true
    = f.input :description
    = f.input :content
    = f.input :summary
    = f.file_field :source

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to 'Back', documents_path, class: 'btn'

app/views/documents/edit.html.slim
.page-header
  h1 Editing document

== render 'form'

app/views/documents/index.html.slim
div.page-header
  h2 
    span list
    small documents

p.text-center= link_to 'Import New Document', new_document_path, class: 'btn btn-primary'

.row
  - @documents.each do |document| 
    .col-md-4= render document

/-table.table.table-striped
/-  thead
/-    tr
/-      th ID
/-      th Name
/-      th Description
/-      th Summary
/-      th Random Sentence
/-      th Actions
/-
/-  tbody
/-  - @documents.each do |document|
/-    tr
/-      /td= link_to_if can?(:show, document), document.id, document_path(document)
/-      td= link_to document.id, document_path(document)
/-      td= document.name
/-      td= document.description
/-      td= document.summary
/-      td= document.sentences.sample
/-      td
/-        == render 'actions', :document => document 
/-        /-#, :locals => { :document => document }
/-        /- if can? :edit, document
/-        /= link_to 'Edit', edit_document_path(document), class: 'btn btn-mini'
/-        /= link_to 'Analyze', analyze_document_path(document), method: :post, data: { confirm: 'Really kickoff analysis?' }, class: 'btn btn-info'
/-        //- if can? :destroy, document
/-        /= link_to 'Destroy', document_path(document), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-mini btn-danger'
/-        /= link_to 'Extract', extract_document_path(@document), method: :post, data: { confirm: 'Really kickoff analysis?' }, class: 'btn btn-info'
/-
/- if can? :create, Document

app/views/documents/new.html.slim
.page-header
  h1 Create document

== render 'form'

app/views/documents/show.html.slim
.page-header
  h1 
    = @document.name
    small review

= render @document

/-.page-header
/-  h1 Document
/-
/-dl
/-  dt Name
/-  dd= @document.name
/-  dt Description
/-  dd= @document.description
/-  dt Content
/-  dd= @document.content[0,140]
/-  dt Source
/-  dd
/-    = link_to @document.source_file_name, @document.source.url
/-  dt Summary
/-  dd= @document.summary
/-
/-  - if @document.worker_progress
/-    dt Worker Status
/-    dd= bootstrap_progress_bar(@document.worker_progress, :color => 'info', :striped => true)
/-
/- if can?(:edit, @document)

/== render 'actions', :document => @document 
/= link_to 'Edit', edit_document_path(@document), class: 'btn'
/
/= link_to 'Extract', extract_document_path(@document), method: :post, data: { confirm: 'Really kickoff analysis?' }, class: 'btn btn-info'
/= link_to 'Analyze', analyze_document_path(@document), method: :post, data: { confirm: 'Really kickoff analysis?' }, class: 'btn btn-info'
= link_to 'Back', documents_path, class: 'btn'

/- if can?(:destroy, @document)
/= link_to'Destroy', document_path(@document), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Flow
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"

  body id=(controller.controller_name) class=(controller.action_name)
    .wrapper
      nav.navbar.navbar-default.navbar-fixed-top role='navigation'
        .navbar-header
          button.button.navbar-toggle data-toggle='collapse' data-target='.navbar-collapse'
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href='/' Flow
        .collapse.navbar-collapse
          ul.nav.navbar-nav.pull-right
            / - if current_user
            /  li.dropdown
            /    a.dropdown-toggle href='#' data-toggle='dropdown'
            /      = current_user.email
            /      b.caret
            /    ul.dropdown-menu
            /      li= link_to 'Sign Out', sign_out_path
            / - else
            /  li= link_to 'Sign In', sign_in_path

      .container
        - flash.each do |name, msg|
          = content_tag :div, raw(msg), class: "alert #{alert_class(name)}"
        = yield
        .push

      footer
        .container
          p &copy; 2013 All rights reserved.

app/views/pages/root.html.slim
javascript:
  /* This little bit of silliness is here to ensure our js feature specs are working. Remove at will. */
  $(document).ready(function() {
    $('.jumbotron p:last').after("<p>Enjoy!</p>")
  });

.jumbotron
  h1 Flow 0.1
  h2= link_to "Your Docs", documents_path
  hr
  h1 Hello, world!
  br
  p Welcome to your newly generated rails application...
  p Meander around the code to see what's been done for you. Many small, and a few not-so-small, customizations have been made.
  p Custom generator templates create views that are bootstrap compatible and specs that are factory-aware and follow best practices.
  p Your application is ready for easy deployment to heroku.